### PR TITLE
50 test readme gen

### PR DESCRIPTION
**Pull request by mikfreedman**

### CODE REVIEW

**Comment by mikfreedman** [comment]
@flavorjones I think the second one makes sense, once I see the diff for how a simple task like this is made it should make it clear how to do it in the future. Before doing this though do you think it's a worthwhile idea? 

I feel like it makes sense to add a diff check in the build but not actually do anything magic like auto commit README changes.

**Comment by flavorjones** [comment]
@mikfreedman after thinking about this, I think I want to just add this as a rake task that is appended onto `default` after `spec` and `license_finder`. That way we could run it locally, and don't need to create an additional concourse task to do it. Objections?

**Comment by flavorjones** [comment]
Gah, encoding! Rage. I can't get this to work, the best I can do I'll put on the branch in a moment, but results in:

```
*** /tmp/readme20190212-20-1en34ew	Tue Feb 12 00:32:46 2019
--- README.md	Tue Feb 12 00:23:06 2019
***************
*** 574,580 ****
  
  [settings]
  end-of-day = "6pm"
! location-icon = "\u{1F30E}"
  meeting-length = "30m"
  start-of-day = "9am"
  </pre>
--- 574,580 ----
  
  [settings]
  end-of-day = "6pm"
! location-icon = "🌎"
  meeting-length = "30m"
  start-of-day = "9am"
  </pre>
```

**Comment by flavorjones** [comment]
@mikfreedman got it to go green, merging it.

**Pull request merged**
