### PR TITLE
launch zoom meetings directly with the zoom cli

### LINKED ISSUE #91: when joining a zoom meeting, use the zoom executable instead of opening a browser window
I'm annoyed by having to open up a browser window. It's distracting.

This post describes how to use the installed `zoom` executable to launch a meeting:

> https://waynewerner.com/blog/launch-zoom-from-the-command-line.html

but the TL;DR is that the following command launches the zoom meeting without opening a browser windows:

```sh
$ zoom "zoommtg://zoom.us/join?action=join&confno=999999999"
ZoomLauncher started.
Zoom not exist at current directory - /home/flavorjones
Zoom path is: /opt/zoom
cmd line: zoommtg://zoom.us/join?action=join&confno=999999999 
$HOME = /home/flavorjones 
export SSB_HOME=/home/flavorjones/.zoom; export QSG_INFO=1; export LD_LIBRARY_PATH=/opt/zoom; /opt/zoom/zoom "zoommtg://zoom.us/join?action=join&confno=999999999 " 
zoom started.
Zoom is running, send message to it: zoommtg://zoom.us/join?action=join&confno=999999999 ;
Exit zoom as another zoom instance is running!
success to create child process,status is 0.
zoom exited normally.
run zoom successfully,exit code is 0.
ZoomLauncher exit.
```

So I'd like to special-case the `join` action for zoom meetings to use this optimized workflow.

### PR DESCRIPTION
**Pull request by flavorjones**
closes #91

### CODE REVIEW

**Comment by flavorjones** [comment]
I want to make one or two more commits here; one of which should get the test coverage back up.

**Comment by flavorjones** [comment]
Ready for review, @mikfreedman

**Comment by mikfreedman** [comment]
Getting the help the wrong way around causes this error

```bash
→ ./bin/calendar-assistant join help
Unable to determine project id.
Traceback (most recent call last):
	14: from ./bin/calendar-assistant:10:in `<main>'
	13: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	12: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	11: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	10: from /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 9: from /Users/user/workspace/calendar-assistant/lib/calendar_assistant/cli/commands.rb:182:in `join'
	 8: from /Users/user/workspace/calendar-assistant/lib/calendar_assistant/calendar_assistant.rb:45:in `in_env'
	 7: from /Users/user/workspace/calendar-assistant/lib/calendar_assistant/config.rb:76:in `in_env'
	 6: from /Users/user/workspace/calendar-assistant/lib/calendar_assistant/calendar_assistant.rb:46:in `block in in_env'
	 5: from /Users/user/workspace/calendar-assistant/lib/calendar_assistant/calendar_assistant.rb:53:in `in_tz'
	 4: from /Users/user/workspace/calendar-assistant/lib/calendar_assistant/calendar_assistant.rb:23:in `in_tz'
	 3: from /Users/user/workspace/calendar-assistant/lib/calendar_assistant/calendar_assistant.rb:54:in `block in in_tz'
	 2: from /Users/user/workspace/calendar-assistant/lib/calendar_assistant/calendar_assistant.rb:47:in `block (2 levels) in in_env'
	 1: from /Users/user/workspace/calendar-assistant/lib/calendar_assistant/cli/commands.rb:183:in `block in join'
/Users/user/workspace/calendar-assistant/lib/calendar_assistant/cli/helpers.rb:36:in `find_av_uri': undefined method `+' for nil:NilClass (NoMethodError)

```

**Comment by flavorjones** [comment]
@mikfreedman WRT macOS, can you try running this command:

```
open zoommtg://zoom.us/join?confno=5445208920
```

and tell me if it works for you?

**Comment by mikfreedman** [comment]
@flavorjones that command works, yes

**Comment by flavorjones** [comment]
OK - I'm going to revise this PR then to use open or xdg-open and that should work for both of us

**Comment by flavorjones** [comment]
@mikfreedman Latest force-push implements this using `open` on macOS and `xdg-open` on Linux, and falling back to browser behavior for other OSes.

**Comment by mikfreedman** [comment]
@flavorjones hey I updated this branch and now I think you need to review it? Good news here is that this works on MacOS too now!

**Pull request merged**
